site_name: Apigentools Docs
nav:
  - Introduction and Quickstart: index.md
  - Workflow: workflow.md
  - Spec Repo: spec_repo.md
  - Reproducibility: reproducible.md
  - CLI Reference: cli.md
  - Changelog: changelog.md
  - Special Files: special_files.md
markdown_extensions:
  - toc:
      permalink: 
  - admonition # used for `!!! note`
