trigger:
  batch: false
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

jobs:
- job: UnitTests
  pool:
    vmImage: "Ubuntu-16.04"
  strategy:
    matrix:
      Py37:
        PYTHON_VERSION: "3.7"
        TOXENV: "py37"
  steps:
    - task: UsePythonVersion@0
      displayName: Use python $(PYTHON_VERSION)
      inputs:
        versionSpec: $(PYTHON_VERSION)
    - script: pip install -e .[tests]
      displayName: Install test dependencies
    - script: sudo npm install -g @openapitools/openapi-generator-cli
      displayName: Install openapi-generator
    - script: pytest
      displayName: Run the test via Pytest
