name: Build

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
  release:
    types:
      - published

jobs:
  build_and_publish_wheel:
    name: Build and publish wheel
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
    environment: "Secure Environment Publish"
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
        # Include all history and tags, needed for building the right version
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install datadog_checks_dev
        run: |
          python -m pip install datadog_checks_dev[cli]==20.0.1

      - name: Build base package
        run: ddev release build apigentools
  
      # Publish wheels to PyPI using Trusted Publishers.
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      # This job needs to run from within the pypi-datadog-checks-base environment. PyPi
      # validates the workflow file name, environment and repository the request is
      # comming from to provide the valid JWT token.
      - name: Release base package to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
          skip-existing: true
          packages-dir: apigentools/.
